### ISSUE TITLE
Sterilization Issue occur while sending photo

### ISSUE THREAD

**Issue by VipinSingh001** [DJ-Raven/java-group-chat#1]
Hi Raven
First of all highly appreciated your efforts in creating this great project We have implemened your project for our office but we are facing one issue i.e. 
We run client jar on different locations and try to send the image file to different clients but at the server end we found the below exception
java.io.InvalidClassException: javax.swing.ImageIcon; local class incompatible: stream classdesc serialVersionUID = -962022720109015502, local class serialVersionUID = 532615968316031794

please try to help to resolve this.
Regards
Vipin Singh
email id - vipinsinghmpec@gmail.com

**Comment by DJ-Raven** [comment]
You need to add serialVersionUID to class Message.java in project Message
and then build to to get jar file, and then add this jar file to both
project server and client,
then run again
code :
private static final long serialVersionUID = 1234L;

**Comment by DJ-Raven** [comment]
For new project chat multi client in current development using socket IO
https://www.youtube.com/playlist?list=PLyt2v1LVXYS366NRBMaiXYGXv0vI2TiMD

**Comment by VipinSingh001** [comment]
Hi DJ-Raven,
As you suggested a solution earlier,  I have done the same but I am facing
again one issue

java.io.InvalidClassException: javax.swing.ImageIcon; local class
incompatible: stream classdesc serialVersionUID = -962022720109015502,
local class serialVersionUID = 532615968316031794

Please help to solve this issue
Regards
Vipin Singh

**Comment by DJ-Raven** [comment]
you can pull or clone new i has updated

**Comment by VipinSingh001** [comment]
Hi DJ-Raven
I have already done your committed changes but still facing the same issue
.
Test Scenario
1. Prepare client jar put client jar into two different machines or another
folder
2. Open client jar with user 'a' and user 'b' now trying to send the image
but the image is not sending while messages are sending
3. facing this exception

java.io.InvalidClassException: javax.swing.ImageIcon; local class
> incompatible: stream classdesc serialVersionUID = -962022720109015502,

please reply asap
Regards

**Comment by DJ-Raven** [comment]
Did you test it by run it on localhost first ?

**Comment by VipinSingh001** [comment]
yes, I did and it's working fine when it comes to different machines facing
issues.

**Comment by DJ-Raven** [comment]
What jdk version you used?

**Comment by DJ-Raven** [comment]
I has test in my labtop connect to desktop ready it works fine when send
image

**Comment by VipinSingh001** [comment]
it's 15.0.2

**Comment by DJ-Raven** [comment]
please test it with JDK 8

**Comment by VipinSingh001** [comment]
Hi DJ-Raven
Can we schedule a meeting? If yes timing and meeting link from your side. I
will show what i am facing ??

**Comment by VipinSingh001** [comment]
Hi DJ Raven
Hope you are doing well. I am waiting for your response. When we can have
meeting session to solve the issue??
Waiting for your reply.
Regards

**Comment by DJ-Raven** [comment]
I will check it again and fix it

**Comment by VipinSingh001** [comment]
Thank you!
Try to solve this issue asap.
